### ISSUE TITLE
Please update WzCompareR2 for 64bit wz structure.

### ISSUE THREAD

**Issue by nanpuhaha** [charlescao460/MapleStory_TFRecord_Preparer#1]
Please update WzCompareR2 for 64bit wz structure.

**Comment by charlescao460** [comment]
Hi, thank you for reminding me of updating WzCompareR2. 
I've updated the WzCompareR2 submodule and resolve the building issue. 
I would really appreciate it if someone can help me test it with 64-bit Wz. 
Could you please test it with 64-bit Wz (seems only KMS has it) and report any issue here?
Thank you!!!

**Comment by nanpuhaha** [comment]
Thank you for the update! I tried to build, but I failed.

I think we should use the WzComparerR2 and CharaSimResource by KENNYSOFT for KMS client.
- https://github.com/KENNYSOFT/WzComparerR2
- https://github.com/KENNYSOFT/CharaSimResource

You can download the recent KMS client with 64-Bit Wz from link below.
- https://sourceforge.net/projects/maplestory-kms/files/1.2.355/

`MapleStoryPathHelper` on `MapleStory.Common` namespace does not work on KMS.

In KMS 64-Bit client, `"Base.wz"` location is `"C:\\Nexon\\Maple\\Data\\Base\\Base.wz"`,
and you can load all wz_Nodes with the code below.

```c#
String wzFilePath = `"C:\\Nexon\\Maple\\Data\\Base\\Base.wz"`;
Wz_Structure wz = new Wz_Structure();
if (wz.IsKMST1125WzFormat(wzFilePath))
{
    wz.LoadKMST1125DataWz(wzFilePath);
}
```

**Comment by charlescao460** [comment]
Hi @nanpuhaha, thanks for the information. Could you please tell me more information about 

> I tried to build, but I failed.

Did you have building errors or runtime errors? Due to some copying mechanism during WzComparerR2's building process, we have to build `WzComparerR2.sln` **before** building `MapleStoryDetectionSampleGenerator.sln`.

Also, introduced by https://github.com/Kagamia/WzComparerR2/pull/173, `CharaSimResource` is now a submodule of `WzComparerR2`. While @KENNYSOFT's fork hasn't introduced such updates yet.  So if you have a previous clone, could you please try this before building `WzComparerR2.sln`
```
cd MapleStoryDetectionSampleGenerator\WzComparerR2
git submodule update --init
```

I will still try to use the original https://github.com/Kagamia/WzComparerR2 as my upstream since it has the most generalization for CMS, TMS, and GMS

**Comment by nanpuhaha** [comment]
Oh, I missed "recursive" option on git clone. 
Thank you @charlescao460.  I learned a new option because of you.

Now, build succeeded! 😎

But Runtime error occurred.. 😭

```shell
> .\MapleStory.MachineLearningSampleGenerator.exe -m 450002001 -x 5 -y 5 -f coco -o ".\output" -p "C:\Nexon\1.2.353(32bit)" --post

MapleStory Location: C:\Nexon\1.2.353(32bit)
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at WzComparerR2.MapRender.UI.MapRenderUIRoot.InitGlobalResource() in D:\MapleStoryDetectionSampleGenerator\WzComparerR2\WzComparerR2.MapRender\UI\MapRenderUIRoot.cs:line 131
   at WzComparerR2.MapRender.UI.MapRenderUIRoot..ctor() in D:\MapleStoryDetectionSampleGenerator\WzComparerR2\WzComparerR2.MapRender\UI\MapRenderUIRoot.cs:line 22
   at WzComparerR2.MapRender.FrmMapRender2.Initialize() in D:\MapleStoryDetectionSampleGenerator\WzComparerR2\WzComparerR2.MapRender\FrmMapRender2.cs:line 153
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.RunOneFrame()
   at MapRender.Invoker.MapRenderInvoker.<>c__DisplayClass36_0.<Launch>b__0() in D:\MapleStoryDetectionSampleGenerator\MapRender.Invoker\MapRenderInvoker.cs:line 107
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

I have to try again with the GMS client instead of KMS client.

**Comment by charlescao460** [comment]
Hi @nanpuhaha , I think that error is because you didn't run `MapleStory.MachineLearningSampleGenerator\bin\Release\net5.0-windows\WzComparerR2.exe` first to generate `Setting.config`. (Yes that's a big pitfall, I'll need to fix it) 
Could you please try again?

**Comment by charlescao460** [comment]
Sorry, it's actually my mistake. I've updated the build instruction on README.md. 
So basically you need to run `MapleStory.MachineLearningSampleGenerator\bin\Release\net5.0-windows\WzComparerR2.exe` once before building `MapleStoryDetectionSampleGenerator.sln`

**Comment by KENNYSOFT** [comment]
Actually KMS version has introduced submodule in 2017. KENNYSOFT/WzComparerR2@da205433302069759b8807b09cab787054c4cead

**Comment by charlescao460** [comment]
@KENNYSOFT Hi, thanks for reminding me that. Sorry I didn't know it was introduced earlier. I saw https://github.com/Kagamia/WzComparerR2/pull/173 was merged recently so I assumed most branches haven't merged upstream yet. 

I apologize that I @ you here in my repo. I thought GitHub won't notify the user in the unrelated repo. Hope it didn't bother you.

**Comment by KENNYSOFT** [comment]
NVM. I've noticed this project by your mention, thanks for your great work and it's really interesting.

**Comment by nanpuhaha** [comment]
@charlescao460 Could you upload the prebuilt binaries on release like WzComparerR2? Then, I can try with your binaries on my computer.

**Comment by charlescao460** [comment]
@nanpuhaha Sure I can set-up a GitHub Action flow when I got a chance, then we have a automatic CI/CD flow like WzComparerR2. 

Are you still experiencing a build issue? If so I can try to help you fix it and update documentation.

**Comment by nanpuhaha** [comment]
@charlescao460 It would be awesome with GitHub Action!

I am free from build issue because of your help, but new runtime errors come to me.

1. it's not working on KMS to find the installed location from registry. (it's okay since we can set the location.)
2. create output directory if not exists. (it's just a suggestion.)
3. (KMS) it cannot find target img "993134200.img", but there is on WzComparerR2.
3. (GMS) Object reference not set to an instance of an object.

---

**1. Cannot find MapleStory installed location from registry on KMS.**
```cmd
D:\MapleStoryDetectionSampleGenerator\MapleStory.MachineLearningSampleGenerator\bin\Debug\net5.0-windows>.\MapleStory.MachineLearningSampleGenerator.exe -m 993134200 -x 5 -y 5 -f coco -o ".\output" --post

D:\MapleStoryDetectionSampleGenerator\MapleStory.MachineLearningSampleGenerator\bin\Debug\net5.0-windows>MapleStory.MachineLearningSampleGenerator 1.0.0

Unhandled exception. System.ArgumentException: Cannot find MapleStory installed location. Please specify it in commandline or retry as Administrator.
   at MapleStory.MachineLearningSampleGenerator.Program.PreRunTest(Options options) in D:\MapleStoryDetectionSampleGenerator\MapleStory.MachineLearningSampleGenerator\Program.cs:line 179
   at MapleStory.MachineLearningSampleGenerator.Program.RunAndReturn(Options options) in D:\MapleStoryDetectionSampleGenerator\MapleStory.MachineLearningSampleGenerator\Program.cs:line 117
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at MapleStory.MachineLearningSampleGenerator.Program.Main(String[] args) in D:\MapleStoryDetectionSampleGenerator\MapleStory.MachineLearningSampleGenerator\Program.cs:line 93
```

Here is the registry values for your reference.
![2021-10-30 21;30;40 i7-8700](https://user-images.githubusercontent.com/9074297/139537177-4b25fe57-c587-468b-9f0f-32d4b74bd56b.png)



**2. OutputPath does not exist.**

```cmd
$ .\MapleStory.MachineLearningSampleGenerator.exe -m 993134200 -x 5 -y 5 -f coco -o ".\output" --post -p "C:\Nexon\Maple\Data\Base"

Unhandled exception. System.ArgumentException: OutputPath .\output does not exist.
   at MapleStory.MachineLearningSampleGenerator.Program.PreRunTest(Options options) in D:\MapleStoryDetectionSampleGenerator\MapleStory.MachineLearningSampleGenerator\Program.cs:line 210
   at MapleStory.MachineLearningSampleGenerator.Program.RunAndReturn(Options options) in D:\MapleStoryDetectionSampleGenerator\MapleStory.MachineLearningSampleGenerator\Program.cs:line 117
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at MapleStory.MachineLearningSampleGenerator.Program.Main(String[] args) in D:\MapleStoryDetectionSampleGenerator\MapleStory.MachineLearningSampleGenerator\Program.cs:line 93
```


**3. (on KMS) it cannot find target img, but there is on WzComparerR2.**

```cmd
D:\MapleStoryDetectionSampleGenerator\MapleStory.MachineLearningSampleGenerator\bin\Debug\net5.0-windows>.\MapleStory.MachineLearningSampleGenerator.exe -m 993134200 -x 5 -y 5 -f coco -o ".\output" --post -p "C:\Nexon\Maple\Data\Base"

D:\MapleStoryDetectionSampleGenerator\MapleStory.MachineLearningSampleGenerator\bin\Debug\net5.0-windows>MapleStory.MachineLearningSampleGenerator 1.0.0

MapleStory Location: C:\Nexon\Maple\Data\Base
Unhandled exception. MapleStory.Common.Exceptions.WzImgNotFoundException: Target Img 993134200.img cannot be found.
   at MapleStory.Common.WzTreeSearcher.SearchForMap(Wz_Node root, String imgText) in D:\MapleStoryDetectionSampleGenerator\MapleStory.Common\WzTreeSearcher.cs:line 64
   at MapRender.Invoker.MapRenderInvoker.LoadMap(String imgText) in D:\MapleStoryDetectionSampleGenerator\MapRender.Invoker\MapRenderInvoker.cs:line 79
   at MapleStory.MachineLearningSampleGenerator.Program.RunAndReturn(Options options) in D:\MapleStoryDetectionSampleGenerator\MapleStory.MachineLearningSampleGenerator\Program.cs:line 125
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at MapleStory.MachineLearningSampleGenerator.Program.Main(String[] args) in D:\MapleStoryDetectionSampleGenerator\MapleStory.MachineLearningSampleGenerator\Program.cs:line 93
```

Here is the screenshot.

![2021-10-30 22;55;33 i7-8700](https://user-images.githubusercontent.com/9074297/139537565-fbf108f9-0336-4ef6-8f0e-62f4d6ed00e7.png)


**4. on GMS, _Object reference not set to an instance of an object._**

```cmd
D:\MapleStoryDetectionSampleGenerator\MapleStory.MachineLearningSampleGenerator\bin\Debug\net5.0-windows>.\MapleStory.MachineLearningSampleGenerator.exe -m 993134200 -x 5 -y 5 -f coco -o ".\output" --post -p "C:\Nexon\Library\maplestory\appdata"

D:\MapleStoryDetectionSampleGenerator\MapleStory.MachineLearningSampleGenerator\bin\Debug\net5.0-windows>MapleStory.MachineLearningSampleGenerator 1.0.0

MapleStory Location: C:\Nexon\Library\maplestory\appdata
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at WzComparerR2.MapRender.UI.MapRenderUIRoot.InitGlobalResource() in D:\MapleStoryDetectionSampleGenerator\WzComparerR2\WzComparerR2.MapRender\UI\MapRenderUIRoot.cs:line 131
   at WzComparerR2.MapRender.UI.MapRenderUIRoot..ctor() in D:\MapleStoryDetectionSampleGenerator\WzComparerR2\WzComparerR2.MapRender\UI\MapRenderUIRoot.cs:line 22
   at WzComparerR2.MapRender.FrmMapRender2.Initialize() in D:\MapleStoryDetectionSampleGenerator\WzComparerR2\WzComparerR2.MapRender\FrmMapRender2.cs:line 153
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.RunOneFrame()
   at MapRender.Invoker.MapRenderInvoker.<>c__DisplayClass36_0.<Launch>b__0() in D:\MapleStoryDetectionSampleGenerator\MapRender.Invoker\MapRenderInvoker.cs:line 107
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

---

This is the what I built. Please check this on your environment.
[net5.0-windows.zip](https://github.com/charlescao460/MapleStoryDetectionSampleGenerator/files/7446860/net5.0-windows.zip)

Could you share the CMS client, if you don't mind? Then, I can try to test with CMS client.

**Comment by charlescao460** [comment]
Hi @nanpuhaha , sorry about the bug. I somehow explain the the wrong method to generate `Setting.config`.
Currently our codes cannot generate `Setting.config` without running `WzComparerR2.exe`. And I didn't see `Setting.config`  in your build file. So, two solutions:
1. Run `WzComparerR2.exe` inside your build directory.
2. Copy a `Setting.config`  to your build directory from whatever WzComparerR2.exe directory you have.

Also, for your suggestion:
1. I will install KMS when I got time and fix that. 
2. Create directory is a good idea. I'll add that
3. I will investigate the problem once I have KMS.
4. Copying or generating the  `Setting.config` should fix the NullReferenceException problem. 

If you want a CMS client, here's the link, you have to download all of them into the same directory:
http://mxd.clientdown.sdo.com/184/Data184.zip
http://mxd.clientdown.sdo.com/184/Data18401.cab
http://mxd.clientdown.sdo.com/184/Data18402.cab
http://mxd.clientdown.sdo.com/184/Data18403.cab
http://mxd.clientdown.sdo.com/184/Data18404.cab
http://mxd.clientdown.sdo.com/184/Maplestory184.exe

**Comment by nanpuhaha** [comment]
@charlescao460 Is there any password on zip file?

**Comment by KENNYSOFT** [comment]
> Is there any password on zip file?

Unknown. You should install it via the Setup exe file.

**Comment by nanpuhaha** [comment]
Thank you! I installed the CMS client.

But it give me the same error with GMS, `System.NullReferenceException: Object reference not set to an instance of an object.`. 😭

So, I tried to debug, and I think I found some reason. 🤔
As you can see the screenshot below, `ConfigManager.ConfigFile.GetSection("WcR2.MapRender")` is `null`.

- `ConfigManager.ConfigFile.GetSection("WcR2.MapRender") == null`
- `ConfigManager.ConfigFile.GetSection("WcR2.Network") == null`
- `ConfigManager.ConfigFile.GetSection("WcR2.ImageHandler") != null`
- `ConfigManager.ConfigFile.GetSection("WcR2.CharaSim") != null`
- `ConfigManager.ConfigFile.GetSection("WcR2") != null`

It looks like `MapRenderConfig` and `NetworkConfig` are not combined(?) with `ConfigManager`.

I hope this will be of some help to you. 🙏

![2021-11-02 12;04;25 i7-8700](https://user-images.githubusercontent.com/9074297/139780752-f540042a-8c4f-462a-9c9a-c0b1622feeaa.png)


**[MapRenderUIRoot.cs](https://github.com/charlescao460/WzComparerR2/blob/81ba71e60b7190cf8b10b944cb53fedc020e1692/WzComparerR2.MapRender/UI/MapRenderUIRoot.cs#L128)**
```c#
private void InitGlobalResource()
{
    var config = MapRender.Config.MapRenderConfig.Default;    //    <--- call stack  "Default"
}
```

**[ConfigSectionBase.cs](https://github.com/charlescao460/WzComparerR2/blob/81ba71e60b7190cf8b10b944cb53fedc020e1692/WzComparerR2.Common/Config/ConfigSectionBase.cs#L20)**
```c#
public static T Default
{
    get
    {
        string secName = ConfigManager.GetSectionName(typeof(T));
        try
        {
            return ConfigManager.ConfigFile.GetSection(secName) as T;    //    <--- break point
        }
        catch (ConfigurationErrorsException e)
        {
            ConfigManager.Reload();
            return ConfigManager.ConfigFile.GetSection(secName) as T;
        }
    }
}
```

**Comment by charlescao460** [comment]
> Hi @nanpuhaha , sorry about the bug. I somehow explain the the wrong method to generate `Setting.config`. Currently our codes cannot generate `Setting.config` without running `WzComparerR2.exe`. And I didn't see `Setting.config` in your build file. So, two solutions:
> 
> 1. Run `WzComparerR2.exe` inside your build directory.
> 2. Copy a `Setting.config`  to your build directory from whatever WzComparerR2.exe directory you have.
> 
> Also, for your suggestion:
> 
> 1. I will install KMS when I got time and fix that.
> 2. Create directory is a good idea. I'll add that
> 3. I will investigate the problem once I have KMS.
> 4. Copying or generating the  `Setting.config` should fix the NullReferenceException problem.
> 
> If you want a CMS client, here's the link, you have to download all of them into the same directory: http://mxd.clientdown.sdo.com/184/Data184.zip http://mxd.clientdown.sdo.com/184/Data18401.cab http://mxd.clientdown.sdo.com/184/Data18402.cab http://mxd.clientdown.sdo.com/184/Data18403.cab http://mxd.clientdown.sdo.com/184/Data18404.cab http://mxd.clientdown.sdo.com/184/Maplestory184.exe

Could you please take a look of above comments and try copying Setting.config?
